import {
  ArrowLeft,
  ArrowRight,
  Frame,
  ImagePlus,
  Bug,
  Check,
  ChevronDown,
  ChevronUp,
  CircleCheckBig,
  Info,
  Clipboard,
  MousePointer2,
  Download,
  Folder,
  Settings,
  Loader2,
  Paintbrush,
  Palette,
  Pen,
  Redo,
  ScanText,
  Circle,
  Square,
  SquareX,
  Highlighter,
  Trash2,
  TriangleAlert,
  Type,
  Undo,
  X,
} from "lucide-react";
import type { IconName } from "./types";
import type { LucideIcon } from "lucide-react";

export const lucideFallbackMap: Record<IconName, LucideIcon> = {
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  frame: Frame,
  "image-plus": ImagePlus,
  bug: Bug,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-up": ChevronUp,
  "circle-check": CircleCheckBig,
  "circle-info": Info,
  clipboard: Clipboard,
  "cursor-default": MousePointer2,
  download: Download,
  folder: Folder,
  gear: Settings,
  loader: Loader2,
  paintbrush: Paintbrush,
  palette: Palette,
  pen: Pen,
  redo: Redo,
  "scan-text": ScanText,
  "shape-circle": Circle,
  "shape-square": Square,
  "square-xmark": SquareX,
  "text-highlight": Highlighter,
  trash: Trash2,
  "triangle-warning": TriangleAlert,
  typography: Type,
  undo: Undo,
  xmark: X,
};
